import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { TimesheetstatusService } from '../timesheetstatus.service';
import { ITimesheetstatus } from '../itimesheetstatus';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

@Component({
  selector: 'app-timesheetstatus-new',
  templateUrl: './timesheetstatus-new.component.html',
  styleUrls: ['./timesheetstatus-new.component.scss'],
})
export class TimesheetstatusNewComponent extends BaseNewComponent<ITimesheetstatus> implements OnInit {
  title: string = 'New Timesheetstatus';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public dialogRef: MatDialogRef<TimesheetstatusNewComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    public pickerDialogService: PickerDialogService,
    public timesheetstatusService: TimesheetstatusService,
    public errorService: ErrorService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(
      formBuilder,
      router,
      route,
      dialog,
      dialogRef,
      data,
      pickerDialogService,
      timesheetstatusService,
      errorService
    );
  }

  ngOnInit() {
    this.entityName = 'Timesheetstatus';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.checkPassedData();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      statusname: ['', Validators.required],
    });

    this.fields = [
      {
        name: 'statusname',
        label: 'statusname',
        isRequired: true,
        isAutoGenerated: false,
        type: FieldType.String,
      },
    ];
  }

  setAssociations() {
    this.associations = [];
    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let timesheetstatus = this.itemForm.getRawValue();

    super.onSubmit(timesheetstatus);
  }
}
