import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { TimesheetdetailsService } from '../timesheetdetails.service';
import { ITimesheetdetails } from '../itimesheetdetails';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { TaskService } from 'src/app/entities/task/task.service';
import { TimeofftypeService } from 'src/app/entities/timeofftype/timeofftype.service';
import { TimesheetService } from 'src/app/entities/timesheet/timesheet.service';

@Component({
  selector: 'app-timesheetdetails-new',
  templateUrl: './timesheetdetails-new.component.html',
  styleUrls: ['./timesheetdetails-new.component.scss'],
})
export class TimesheetdetailsNewComponent extends BaseNewComponent<ITimesheetdetails> implements OnInit {
  title: string = 'New Timesheetdetails';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public dialogRef: MatDialogRef<TimesheetdetailsNewComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    public pickerDialogService: PickerDialogService,
    public timesheetdetailsService: TimesheetdetailsService,
    public errorService: ErrorService,
    public taskService: TaskService,
    public timeofftypeService: TimeofftypeService,
    public timesheetService: TimesheetService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(
      formBuilder,
      router,
      route,
      dialog,
      dialogRef,
      data,
      pickerDialogService,
      timesheetdetailsService,
      errorService
    );
  }

  ngOnInit() {
    this.entityName = 'Timesheetdetails';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.checkPassedData();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      hours: [''],
      notes: [''],
      workdate: ['', Validators.required],
      taskid: [''],
      taskDescriptiveField: [''],
      timeofftypeid: [''],
      timeofftypeDescriptiveField: [''],
      timesheetid: ['', Validators.required],
      timesheetDescriptiveField: ['', Validators.required],
    });

    this.fields = [
      {
        name: 'workdate',
        label: 'workdate',
        isRequired: true,
        isAutoGenerated: false,
        type: FieldType.Date,
      },
      {
        name: 'notes',
        label: 'notes',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'hours',
        label: 'hours',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.Number,
      },
    ];
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'taskid',
            value: undefined,
            referencedkey: 'id',
          },
        ],
        isParent: false,
        table: 'task',
        type: 'ManyToOne',
        service: this.taskService,
        label: 'task',
        descriptiveField: 'taskDescriptiveField',
        referencedDescriptiveField: 'id',
      },
      {
        column: [
          {
            key: 'timeofftypeid',
            value: undefined,
            referencedkey: 'id',
          },
        ],
        isParent: false,
        table: 'timeofftype',
        type: 'ManyToOne',
        service: this.timeofftypeService,
        label: 'timeofftype',
        descriptiveField: 'timeofftypeDescriptiveField',
        referencedDescriptiveField: 'id',
      },
      {
        column: [
          {
            key: 'timesheetid',
            value: undefined,
            referencedkey: 'id',
          },
        ],
        isParent: false,
        table: 'timesheet',
        type: 'ManyToOne',
        service: this.timesheetService,
        label: 'timesheet',
        descriptiveField: 'timesheetDescriptiveField',
        referencedDescriptiveField: 'id',
      },
    ];
    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let timesheetdetails = this.itemForm.getRawValue();

    super.onSubmit(timesheetdetails);
  }
}
