import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { TaskService } from '../task.service';
import { ITask } from '../itask';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { ProjectService } from 'src/app/entities/project/project.service';

@Component({
  selector: 'app-task-details',
  templateUrl: './task-details.component.html',
  styleUrls: ['./task-details.component.scss'],
})
export class TaskDetailsComponent extends BaseDetailsComponent<ITask> implements OnInit {
  title = 'Task';
  parentUrl = 'task';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public taskService: TaskService,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService,
    public projectService: ProjectService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, pickerDialogService, taskService, errorService);
  }

  ngOnInit() {
    this.entityName = 'Task';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      description: [''],
      id: [{ value: '', disabled: true }, Validators.required],
      isactive: [false, Validators.required],
      name: ['', Validators.required],
      projectid: [''],
      projectDescriptiveField: [''],
    });

    this.fields = [
      {
        name: 'name',
        label: 'name',
        isRequired: true,
        isAutoGenerated: false,
        type: FieldType.String,
      },
      {
        name: 'isactive',
        label: 'isactive',
        isRequired: true,
        isAutoGenerated: false,
        type: FieldType.Boolean,
      },
      {
        name: 'description',
        label: 'description',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
    ];
  }

  onItemFetched(item: ITask) {
    this.item = item;
    this.itemForm.patchValue(item);
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'projectid',
            value: undefined,
            referencedkey: 'id',
          },
        ],
        isParent: false,
        table: 'project',
        type: 'ManyToOne',
        label: 'project',
        service: this.projectService,
        descriptiveField: 'projectDescriptiveField',
        referencedDescriptiveField: 'id',
      },
      {
        column: [
          {
            key: 'taskid',
            value: undefined,
            referencedkey: 'id',
          },
        ],
        isParent: true,
        table: 'timesheetdetails',
        type: 'OneToMany',
        label: 'timesheetdetails',
      },
      {
        column: [
          {
            key: 'taskid',
            value: undefined,
            referencedkey: 'id',
          },
        ],
        isParent: true,
        table: 'usertask',
        type: 'OneToMany',
        label: 'usertasks',
      },
    ];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let task = this.itemForm.getRawValue();

    super.onSubmit(task);
  }
}
